base domain models
UdovikArtem/FinPortfolio pull request #1
Opened 2024-07-07 17:44 UTC by ShinzTer

Main page:
![Screenshot_finPortfolio_main](https://github.com/UdovikArtem/FinPortfolio/assets/99730683/5bbd46a1-f1d9-4afc-bed2-a9c772789b7f)
Portfolio page:
![Screenshot_finPortfolio_portfolio](https://github.com/UdovikArtem/FinPortfolio/assets/99730683/aaf09160-83dd-4617-8a7f-2dcddddd8196)
Assets page:
![Screenshot_finPortfolio_assets](https://github.com/UdovikArtem/FinPortfolio/assets/99730683/c720e05b-544d-4d3c-abbe-874df8a37bd1)

2024-07-07 17:51 UTC, UdovikArtem approved these changes

2024-07-07 18:18 UTC, pzinkevich42innowise requested changes

2024-07-07 18:18 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/finportfolio/fragments/assets/AssetFragment.kt
> +            findNavController().navigate(R.id.action_assetFragment_to_mainFragment)
Навигация через Directions и saveArgs

2024-07-07 18:18 UTC, pzinkevich42innowise commented on app/src/main/res/layout/fragment_asset.xml
> +        android:text="@string/main_page" />
А чем тулбар с кнопкой назад не устроил?

2024-07-07 18:18 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/finportfolio/fragments/portfolio/PortfolioFragment.kt
> +            findNavController().navigate(R.id.action_portfolioFragment_to_mainFragment)
А если я жест назад выполню, меня с главной перенесёт в портфель?

2024-07-08 14:18 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/finportfolio/entity/Asset.kt
Это вся доменная модель? Или будет расширяться далее?

2024-07-08 14:20 UTC, pzinkevich42innowise requested changes

2024-07-08 14:20 UTC, pzinkevich42innowise commented on app/src/main/res/layout/fragment_asset.xml
> +<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
Зачем тут Linear?

2024-07-08 14:20 UTC, pzinkevich42innowise commented on app/src/main/res/layout/fragment_portfolio.xml
> +<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
Зачем нужен пустой лайнир?

2024-07-10 20:22 UTC, pzinkevich42innowise requested changes

2024-07-10 20:22 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/finportfolio/entity/Asset.kt
> +    open val price: Double
цена чего? в чём измеряется? она точно нужна внутри Asset?

2024-07-10 20:22 UTC, pzinkevich42innowise commented on app/src/main/res/layout/fragment_asset.xml
> +</androidx.recyclerview.widget.RecyclerView>
```suggestion
    tools:context=".fragments.assets.AssetFragment"/>
```

2024-07-10 20:30 UTC, pzinkevich42innowise approved these changes

2024-07-10 20:31 UTC, merged