Settings
UdovikArtem/FinPortfolio pull request #3
Opened 2024-07-10 19:50 UTC by UdovikArtem

### Add settingFragment and SettingStore
![image](https://github.com/UdovikArtem/FinPortfolio/assets/99731005/18326ffc-55f1-442f-a16b-cfbdbaccb224)
Setting
![image](https://github.com/UdovikArtem/FinPortfolio/assets/99731005/c7b43d54-ab3e-4d5f-90c8-da88441f056c)

2024-07-10 19:52 UTC, ShinzTer approved these changes

2024-07-10 20:29 UTC, pzinkevich42innowise requested changes

2024-07-10 20:29 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/finportfolio/fragments/assets/AssetFragment.kt
> +    ): FragmentAssetBinding = FragmentAssetBinding.inflate(inflater, container, false)
```suggestion
    ) = FragmentAssetBinding.inflate(inflater, container, false)
```

2024-07-10 20:29 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/finportfolio/fragments/assets/AssetFragment.kt
> +        adapter.submitItems(AssetRepository.getAssets())
ViewModel?

2024-07-10 20:29 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/finportfolio/fragments/portfolio/PortfolioFragment.kt
> +    ): FragmentPortfolioBinding = FragmentPortfolioBinding.inflate(inflater, container, false)
аналогично

2024-07-10 20:29 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/finportfolio/fragments/setting/SettingFragment.kt
> +    private lateinit var settingStore: SettingStore
ViewModel?

2024-07-10 20:29 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/finportfolio/fragments/setting/SettingFragment.kt
> +            adapter.setDropDownViewResource(android.R.layout.simple_spinner_dropdown_item)
не забудь потом переписать на StringSelector

2024-07-10 20:29 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/finportfolio/fragments/setting/SettingFragment.kt
> +        }
жоско и низкоуровнево, но штош поделац

2024-07-10 20:29 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/finportfolio/rv/AssetAdapter.kt
> +        return AssetViewHolder(
Краткая форма?

2024-07-10 20:29 UTC, pzinkevich42innowise commented on app/src/main/res/layout/fragment_asset.xml
> +<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
Зачем тут LinearLayout?

2024-07-10 20:29 UTC, pzinkevich42innowise commented on app/src/main/res/layout/fragment_portfolio.xml
> +<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
Что это за лейаут?

2024-07-11 13:36 UTC, Valentin2508247 requested changes

2024-07-11 13:36 UTC, Valentin2508247 commented on app/src/main/java/com/example/finportfolio/data/setting/SettingStore.kt
должен быть в Domain слое
нарушает dependency rule

2024-07-11 13:36 UTC, Valentin2508247 commented on app/src/main/java/com/example/finportfolio/data/setting/SettingStoreImpl.kt
> +class SettingStoreImpl(context: Context) : SettingStore {
давай добавим в Hilt

2024-07-11 13:36 UTC, Valentin2508247 commented on app/src/main/java/com/example/finportfolio/di/AppModule.kt
> +    fun provideSettingStore(@ApplicationContext context: Context): SettingStore {
можно поменять на Binds и передать объект SettingStoreImpl в параметры

2024-07-11 13:36 UTC, Valentin2508247 commented on app/src/main/java/com/example/finportfolio/fragments/assets/AssetFragment.kt
> +class AssetFragment : BaseFragment<FragmentAssetBinding>() {
@AndroidEntryPoint

2024-07-11 13:36 UTC, Valentin2508247 commented on app/src/main/java/com/example/finportfolio/fragments/assets/AssetFragment.kt
> +        viewModel.model.observe(viewLifecycleOwner) { assets ->
непонятно что за LiveData
лучше поменять нейминг с model на что-то другое

2024-07-11 13:36 UTC, Valentin2508247 commented on app/src/main/java/com/example/finportfolio/fragments/assets/AssetViewModel.kt
> +class AssetViewModel : ViewModel() {
@HiltViewModel + @Inject constructor

2024-07-11 13:36 UTC, Valentin2508247 commented on app/src/main/java/com/example/finportfolio/fragments/assets/AssetViewModel.kt
> +        _model.value = AssetRepository.getAssets()
через DI

2024-07-11 13:36 UTC, Valentin2508247 commented on app/src/main/java/com/example/finportfolio/fragments/portfolio/PortfolioFragment.kt
> +class PortfolioFragment : BaseFragment<FragmentPortfolioBinding>() {
@AndroidEntryPoint

2024-07-11 13:36 UTC, Valentin2508247 commented on app/src/main/java/com/example/finportfolio/fragments/setting/SettingViewModel.kt
> +        return _model.value ?: "USD"
хотелось бы обратиться к data-слою

2024-07-15 09:21 UTC, Valentin2508247 requested changes

2024-07-15 09:21 UTC, Valentin2508247 commented on app/src/main/java/com/example/finportfolio/data/asset/LocalAssetDataSource.kt
> +    private val assets: HashMap<Int, Asset> = HashMap(
private val assets: Map<Int, Asset> = HashMap(

2024-07-16 08:28 UTC, Valentin2508247 approved these changes

2024-07-16 10:23 UTC, merged