Feature/string selector
UdovikArtem/FinPortfolio pull request #4
Opened 2024-07-21 20:59 UTC by UdovikArtem

Add String Selector for currencies setting screen

![image](https://github.com/user-attachments/assets/007fd247-e0cc-45ce-b7b9-3385744b79f0)

2024-07-22 12:03 UTC, ShinzTer approved these changes

2024-07-22 16:33 UTC, AlexVLive requested changes
В целом все хорошо, есть незначительные замечания

2024-07-22 16:33 UTC, AlexVLive commented on app/src/main/java/com/example/finportfolio/data/local/LocalCurrencyDataSource.kt
> +    private val defaultCurrencies = Currency.entries.toTypedArray()
Переменная кажется излишней. Лaконичней будет:
override fun getCurrencies(): List<Currency> = Currency.entries.toTypedArray().toList()

2024-07-22 16:33 UTC, AlexVLive commented on app/src/main/java/com/example/finportfolio/fragments/setting/SettingFragment.kt
> +        private const val CURRENCY_NAME = "currencyName"
Если в companion object все val являются private, можно сделать private companion object и убрать private с const val

2024-07-22 16:33 UTC, AlexVLive commented on app/src/main/java/com/example/finportfolio/fragments/setting/SettingFragment.kt
> +            binding.defaultCurrency.setOnClickListener {
Тут, похоже, нет необходимости в использовании .apply{}

2024-07-22 16:33 UTC, AlexVLive commented on app/src/main/java/com/example/finportfolio/fragments/setting/SettingFragment.kt
>              viewModel.currencyModel.observe(viewLifecycleOwner) {
Почему это в binding.apply {}? Setup Observables не должно быть в этой scope-функции

2024-07-23 06:34 UTC, AlexVLive approved these changes
LGTM

2024-07-23 07:14 UTC, merged

2024-07-23 07:50 UTC, Valentin2508247 requested changes

2024-07-23 07:50 UTC, Valentin2508247 commented on app/src/main/java/com/example/finportfolio/fragments/setting/SettingFragment.kt
> +        private const val KEY_CURRENCY = "currencyKey"
сделай общие ключи для двух фрагментов

2024-07-23 07:50 UTC, Valentin2508247 commented on app/src/main/java/com/example/finportfolio/fragments/setting/stringselector/CurrencyStringSelector.kt
> +        private const val KEY_CURRENCY = "currencyKey"
сделай общие ключи для двух фрагментов

2024-07-23 07:50 UTC, Valentin2508247 commented on app/src/main/java/com/example/finportfolio/fragments/setting/stringselector/CurrencyStringSelector.kt
> +                binding.bottomSheetLayout.addView(textView)
странно, но окей
в случае, если currencies.observe вызовется несколько раз будут duplicate элементы
как вариант можно чистить элементы при observe