Add asset details
UdovikArtem/FinPortfolio pull request #5
Opened 2024-07-28 14:02 UTC by UdovikArtem

![image](https://github.com/user-attachments/assets/85d7c312-1d75-4841-96f0-a82d189644c0)

2024-07-28 14:03 UTC, ShinzTer approved these changes

2024-07-29 07:46 UTC, Valentin2508247 requested changes

2024-07-29 07:46 UTC, Valentin2508247 commented on app/src/main/java/com/example/finportfolio/fragments/assetdetails/AssetDetailsFragment.kt
> +                Toast.makeText(context, "Asset wasn't found", Toast.LENGTH_SHORT).show()
в ресурсы

2024-07-29 07:46 UTC, Valentin2508247 commented on app/src/main/res/layout/fragment_asset_details.xml
лучше использовать ListView

2024-07-29 12:48 UTC, Valentin2508247 requested changes

2024-07-29 12:48 UTC, Valentin2508247 commented on app/src/main/res/layout/fragment_asset_details.xml
> +    <ListView
сори, я перепутал ListView с LinearLayout
я имел ввиду что в этом layout не нужен ConstraintLayout и можно ограничится LinearLaout

2024-07-29 13:25 UTC, Valentin2508247 approved these changes

2024-07-29 15:09 UTC, merged